### ISSUE TITLE
[BLOG] Add mention of buttonball tree, Sunderland

### ISSUE THREAD

**Issue by ysahil97** [martiansideofthemoon/martiansideofthemoon.github.io#2]
Hi Kalpesh

Thanks for creating such a unique blogpost highlighting the life and uniqueness of Amherst and Western Massachusetts in general.  It's really informative. I created this issue to highlight one of the unique natural offerings which Amherst provides. There's a huge tree called ButtonBall tree, which is like the __largest__ tree on the east side of the Missisippi River.
Wiki: https://en.wikipedia.org/wiki/Buttonball_Tree
Reddit Post (I found out from here): https://www.reddit.com/r/marijuanaenthusiasts/comments/11tx520/the_buttonball_tree_in_sunderland_ma_thought_to/

Is it possible to add a mention of this in your blog post dated March 28 2022 as well? I was a bit amazed when I saw that tree in person.

**Comment by martiansideofthemoon** [comment]
Oh wow that's great to know! I will go and check it out. Please feel free to make a PR to add this in
